language: java
jdk:
	- openjdk

cache:
	directories:
		- "$HOME/.cache"

jobs:
	- stage:
	  name: 'Deploy to development environment'
	  script:
	   - mvn clean install
	   - cp .travis.settings.xml $HOME/.m2/settings.xml
	   - mvn deploy -DmuleDeploy -Dserver=$server -Dworkers=$workers $ workerType=$workerType -Denvironment=$environment -DmuleVersion=$muleVersion - DappName=$appName 
	if: branch = dev
