language: java

jdk:
  - openjdk8

cache:
  directories:
  - "$HOME/.cache"

script:
  - mkdir -p $HOME/.m2
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn clean install
  - mvn deploy -DmuleDeploy -Dserver=$server -Dworkers=$workers $ workerType=$workerType -Denvironment=$environment -DmuleVersion=$muleVersion - DappName=$appName 
if: branch = dev
